name: Release

on:
  push:
    branches: [ main ]

jobs:
  upload-artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Prepare environment
        run: |
          mkdir reports

      - name: Generate LSS report PDF
        uses: docker://pandoc/latex:2.18
        with:
          args: -d ./pandoc/latex.yml -o reports/LSSReport.pdf -M date:${{steps.date.outputs.date}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lss-report-${{ steps.date.outputs.date }}
          path: reports
  release:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: lss-report
          path: reports
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 16